### PR TITLE
Fix for #98 and #99

### PR DESCRIPTION
**Pull request by parvusdomus**
## Changes
- new feature

Fixes #(number of the issue fixed by your PR, if it exists)

### CODE REVIEW

**Review by pplans — APPROVED** [review]
makes me think we might use a new LexArcanaDice method that rolls without threshold, I can take care of that tomorrow

**Comment by parvusdomus** [comment]
Using "0" as the threshold does that effect (it doesn't give you a "success" or "failure" message) I thought it was intended to work this way.

**Comment by pplans** [comment]
oh it is you did well, I am just thinking "out loud" if that design is nice or not :D I do that all time at work no worries parvus

**Comment by pplans** [comment]
by the way, I merged the PRs :)

**Pull request merged**
